import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
const baseUrl = process.env.QA_BASE_URL || 'http://127.0.0.1:3000';
const screenshotDir = process.env.QA_SCREENSHOT_DIR;
import assert from 'node:assert/strict';
const browser = await chromium.launch({headless: true, ...(process.env.QA_CHROMIUM_PATH ? {executablePath:process.env.QA_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']} : {})});
const page = await browser.newPage({viewport:{width:1440,height:1000},timezoneId:'Africa/Johannesburg'});
const errors=[]; page.on('pageerror', e=>errors.push(e.message));
await page.addInitScript(() => {
  class Recognition { start(){window.qaRecognition=this;} stop(){} }
  window.SpeechRecognition=Recognition;
  window.qaSaid=[];
  window.speechSynthesis.speak=u=>{window.qaSaid.push(u.text);};
  window.speechSynthesis.cancel=()=>{};
});
const command = async text => { await page.evaluate(text=>window.qaRecognition.onresult({results:[[{transcript:text}]]}),text); await page.waitForTimeout(100); };
const archiveLoaded = page.waitForResponse(r=>r.url().includes('/api/stories'));
await page.goto(baseUrl);
await archiveLoaded;
await page.getByRole('button',{name:'Next →',exact:true}).waitFor();
const storyTitle=()=>page.locator('article h2').innerText();
const first=await storyTitle();
await page.getByRole('button',{name:'Talk to Absurdity'}).click();
await command('next'); const second=await storyTitle(); assert.notEqual(second,first);
await command('next'); const third=await storyTitle(); assert.notEqual(third,second);
await command('favorite');
await command('favorites');
assert.match(await page.locator('nav button[aria-current]').innerText(),/Favorites/);
assert.equal(await storyTitle(),third);
await page.reload();
await page.getByRole('button',{name:/^Favorites/}).click();
await page.waitForFunction(title=>document.querySelector('article h2')?.textContent===title,third);
assert.equal(await storyTitle(),third);
await page.getByRole('button',{name:'History',exact:true}).click();
await page.getByRole('textbox',{name:'Search stories'}).fill('South Africa');
assert.match(await page.locator('aside').innerText(),/Goat walks into/);
await page.getByRole('textbox',{name:'Search stories'}).fill('no-results-ever');
await page.getByText('No archived stories match this search and timeframe.').first().waitFor();
assert.match(await page.locator('aside').innerText(),/No archived stories/);
await page.getByRole('button',{name:'New stories',exact:true}).click();
const before=await page.getByRole('button',{name:'Dismiss story',exact:true}).count();
await page.getByRole('button',{name:'Dismiss story',exact:true}).first().click();
assert.equal(await page.getByRole('button',{name:'Dismiss story',exact:true}).count(),before-1);
await page.reload();
await page.getByRole('button',{name:/Restore dismissed/}).waitFor();
assert.equal(await page.getByRole('button',{name:'Dismiss story',exact:true}).count(),before-1);
await page.getByRole('button',{name:/Restore dismissed/}).click();
assert.equal(await page.getByRole('button',{name:'Dismiss story',exact:true}).count(),before);
await page.getByRole('button',{name:'Read aloud'}).click();
await page.waitForFunction(()=>window.qaSaid.length>0);
await page.getByRole('button',{name:'Stop reading'}).click();
await page.route('**/api/narrate',async route=>{await new Promise(r=>setTimeout(r,300));await route.fulfill({status:503,contentType:'application/json',body:'{}'});});
const saidBefore=await page.evaluate(()=>window.qaSaid.length);
await page.getByRole('button',{name:'Read aloud'}).click();
await page.getByRole('button',{name:'Preparing…'}).click();
await page.waitForTimeout(500);
assert.equal(await page.evaluate(()=>window.qaSaid.length),saidBefore);
assert.equal(await page.locator('a[target="_blank"]').count()>0,true);
if (screenshotDir) { await mkdir(screenshotDir,{recursive:true}); await page.screenshot({path:screenshotDir+'/desktop.png',fullPage:true}); }
await page.setViewportSize({width:360,height:800});
await page.getByRole('button',{name:'History',exact:true}).click();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
if (screenshotDir) await page.screenshot({path:screenshotDir+'/mobile.png',fullPage:true});
await page.getByRole('button',{name:'Talk to Absurdity'}).click();
await page.evaluate(()=>{window.qaRecognition.onerror({error:'not-allowed'});window.qaRecognition.onend();});
await page.getByRole('button',{name:'Talk to Absurdity'}).waitFor();
assert.deepEqual(errors,[]);
console.log('PASS desktop/mobile, repeated voice navigation, favorites command, storage reload, search, dismiss/restore, source links, speech fallback, cancel-pending narration, no page errors');
await browser.close();
