import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
const baseUrl = process.env.QA_BASE_URL || 'http://127.0.0.1:3000';
const screenshotDir = process.env.QA_SCREENSHOT_DIR;
import assert from 'node:assert/strict';
const browser = await chromium.launch({headless: true, ...(process.env.QA_CHROMIUM_PATH ? {executablePath:process.env.QA_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']} : {})});
const page = await browser.newPage({viewport:{width:1440,height:1000},timezoneId:'Africa/Johannesburg'});
const errors=[]; page.on('pageerror', e=>errors.push(e.message));
const researchRequests=[]; page.on('request', r=>{if(r.url().includes('/api/research') && r.method()==='POST') researchRequests.push(r.url());});
await page.route('**/api/research*', route => route.fulfill({json:{run:null}}));
await page.addInitScript(() => {
  class Recognition { start(){window.qaRecognition=this;window.qaRecognitionStarts=(window.qaRecognitionStarts||0)+1;} stop(){queueMicrotask(()=>this.onend?.());} }
  window.SpeechRecognition=Recognition;
  window.qaSaid=[];
  window.speechSynthesis.speak=u=>{window.qaSaid.push(u.text); window.qaUtterance=u;};
  window.speechSynthesis.cancel=()=>{};
});
const command = async text => { await page.evaluate(text=>window.qaRecognition.onresult({results:[[{transcript:text}]]}),text); await page.waitForTimeout(100); };
const archiveLoaded = page.waitForResponse(r=>r.url().includes('/api/stories'));
await page.goto(baseUrl);
await archiveLoaded;
await page.getByRole('button',{name:'Next story',exact:true}).waitFor();
const storyTitle=()=>page.locator('article h2').innerText();
const first=await storyTitle();
await page.getByRole('button',{name:'Talk to Absurdity'}).click();
await command('next'); const second=await storyTitle(); assert.notEqual(second,first);
await command('next'); const third=await storyTitle(); assert.notEqual(third,second);
await command('favorite');
await command('favorites');
assert.match(await page.locator('nav button[aria-current]').innerText(),/Favorites/);
assert.equal(await storyTitle(),third);
await page.reload();
await page.getByRole('button',{name:/^Favorites/}).click();
await page.waitForFunction(title=>document.querySelector('article h2')?.textContent===title,third);
assert.equal(await storyTitle(),third);
await page.getByRole('button',{name:'History',exact:true}).click();
assert.equal(await page.getByRole('textbox',{name:'Search stories'}).count(),0);
await page.getByRole('button',{name:'Talk to Absurdity'}).click();
const search = async text => {
  const response=page.waitForResponse(r=>r.url().includes('/api/chat'));
  await command(text); await response;
  await page.waitForFunction(()=>window.qaSaid.length>0);
  await page.getByRole('button',{name:'Stop reading'}).click();
};
await search('find South African stories');
assert.match(await page.locator('aside').innerText(),/Goat walks into/);
await search('find no-results-ever');
await page.getByText('No archived stories match this search and timeframe.').first().waitFor();
assert.match(await page.locator('aside').innerText(),/No archived stories/);
await search('show older animal stories');
await page.getByText('No archived stories match this search and timeframe.').first().waitFor();
await search('find animal stories in my favorites');
assert.equal(await storyTitle(),third);
// Conversational turns carry context, speak replies, suppress echo, and resume listening.
const turns=[];
await page.route('**/api/chat',async route=>{
  const body=route.request().postDataJSON(); turns.push(body);
  const action={text:'The article is a demonstration fixture.',action:'none',view:null,storyId:null,query:null,from:null,before:null,read:false};
  await route.fulfill({contentType:'application/json',body:JSON.stringify({text:action.text,action,provider:'groq',mode:'demo'})});
});
await command('tell me more about this story');
await page.getByText('The article is a demonstration fixture.',{exact:true}).first().waitFor();
await page.getByRole('button',{name:'Stop reading'}).waitFor();
const titleBeforeEcho=await storyTitle();
await command('next');
assert.equal(await storyTitle(),titleBeforeEcho);
const startsBefore=await page.evaluate(()=>window.qaRecognitionStarts);
await page.evaluate(()=>window.qaUtterance.onend());
assert.ok(await page.evaluate(()=>window.qaRecognitionStarts)>startsBefore);
await command('is it real?');
await page.waitForFunction(()=>window.qaSaid.length>1);
await page.getByRole('button',{name:'Stop reading'}).waitFor();
assert.equal(turns[1].history.at(-1).content,'The article is a demonstration fixture.');
assert.equal(turns[0].storyId,turns[1].storyId);
await page.getByRole('button',{name:'Stop reading'}).click();
await page.unroute('**/api/chat');
// A Groq selection outside a favorites search opens the archive and reads that article.
let selectedReply;
await page.route('**/api/chat',async route=>{
  selectedReply=(await (await page.request.get(baseUrl+'/api/stories?scope=history')).json()).stories[0];
  const action={text:'Opening that story.',action:'select',view:null,storyId:selectedReply.id,query:null,from:null,before:null,read:true};
  await route.fulfill({contentType:'application/json',body:JSON.stringify({text:action.text,action,provider:'groq',mode:'demo'})});
});
await command('please open the emu article and read it');
await page.getByRole('button',{name:'Stop reading'}).waitFor();
assert.equal(await storyTitle(),selectedReply.title);
assert.equal(await page.locator('nav button[aria-current]').innerText(),'History');
assert.match(await page.evaluate(()=>window.qaSaid.at(-1)),/Escaped emu/);
await page.getByRole('button',{name:'Stop reading'}).click();
await page.unroute('**/api/chat');
// Cancelling a delayed conversation must not navigate or speak after cancellation.
await page.route('**/api/chat',async route=>{
  await new Promise(r=>setTimeout(r,400));
  const action={text:'Opening favorites.',action:'view',view:'favorites',storyId:null,query:null,from:null,before:null,read:false};
  await route.fulfill({contentType:'application/json',body:JSON.stringify({text:action.text,action,provider:'groq',mode:'demo'})});
});
const beforeCancelledReply=await page.evaluate(()=>window.qaSaid.length);
await command('please take me to my saved picks');
await page.getByRole('button',{name:'Stop response'}).click();
await page.waitForTimeout(500);
assert.equal(await page.evaluate(()=>window.qaSaid.length),beforeCancelledReply);
assert.equal(await page.locator('nav button[aria-current]').innerText(),'History');
await page.unroute('**/api/chat');
await command('stop listening');
if (await page.getByRole('button',{name:'Dismiss reply'}).count()) await page.getByRole('button',{name:'Dismiss reply'}).click();
await page.route('**/api/research*', route => route.fulfill({json:{run:{id:'qa-fetch',status:'complete',selected:0},started:false}}));
await page.getByRole('button',{name:'Refresh stories',exact:true}).click();
await page.getByText('The last fetch is still recent. A new fetch is available in a few minutes.').waitFor();
await page.getByRole('button',{name:'Home',exact:true}).first().click();
const before=await page.locator('.story-row').count();
await page.getByRole('button',{name:'Dismiss story',exact:true}).first().click();
assert.equal(await page.locator('.story-row').count(),before-1);
await page.reload();
await page.getByRole('button',{name:/Restore dismissed/}).waitFor();
assert.equal(await page.locator('.story-row').count(),before-1);
await page.getByRole('button',{name:/Restore dismissed/}).click();
assert.equal(await page.locator('.story-row').count(),before);
await page.getByRole('button',{name:'Read aloud'}).click();
await page.waitForFunction(()=>window.qaSaid.length>0);
await page.getByRole('button',{name:'Stop reading'}).click();
await page.route('**/api/narrate',async route=>{await new Promise(r=>setTimeout(r,300));await route.fulfill({status:503,contentType:'application/json',body:'{}'});});
const saidBefore=await page.evaluate(()=>window.qaSaid.length);
await page.getByRole('button',{name:'Read aloud'}).click();
await page.getByRole('button',{name:'Preparing…'}).click();
await page.waitForTimeout(500);
assert.equal(await page.evaluate(()=>window.qaSaid.length),saidBefore);
assert.equal(await page.locator('a[target="_blank"]').count()>0,true);
assert.equal(await page.evaluate(()=>document.querySelector('.story-text')?.nextElementSibling?.classList.contains('source-section')),true);
for (const viewport of [{width:1366,height:768},{width:1280,height:720},{width:360,height:640},{width:844,height:390}]) {
  await page.setViewportSize(viewport);
  const bounds=await page.evaluate(()=>({width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,viewportWidth:innerWidth,viewportHeight:innerHeight}));
  assert.ok(bounds.width<=bounds.viewportWidth && bounds.height<=bounds.viewportHeight,JSON.stringify(bounds));
  await page.getByRole('button',{name:'Talk to Absurdity'}).scrollIntoViewIfNeeded();
  assert.equal(await page.evaluate(()=>document.scrollingElement.scrollTop),0);
}
await page.setViewportSize({width:1366,height:768});
if (screenshotDir) { await mkdir(screenshotDir,{recursive:true}); await page.screenshot({path:screenshotDir+'/desktop.png',fullPage:true}); }
await page.setViewportSize({width:360,height:800});
await page.getByRole('button',{name:'History',exact:true}).click();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
if (screenshotDir) await page.screenshot({path:screenshotDir+'/mobile.png',fullPage:true});
await page.getByRole('button',{name:'Talk to Absurdity'}).click();
await page.evaluate(()=>{window.qaRecognition.onerror({error:'not-allowed'});window.qaRecognition.onend();});
await page.getByRole('button',{name:'Talk to Absurdity'}).waitFor();
await page.getByRole('textbox',{name:'Ask Absurdity to navigate'}).fill('open history');
await page.getByRole('button',{name:'Send instruction'}).click();
assert.equal(await page.locator('nav button[aria-current]').innerText(),'History');
await page.getByRole('button',{name:'Close instruction box'}).click();
assert.equal(researchRequests.length,1);
assert.deepEqual(errors,[]);
console.log('PASS conversation context, pause/resume, echo suppression, cancel-pending conversation, single-page laptop/phone/landscape layout, inline sources, requested archive search only, voice navigation, favorites, storage reload, dismiss/restore, speech fallback, cancel-pending narration, microphone denial with typed navigation, no page errors');
await browser.close();
