import type { Briefing } from "./types";

export const demoBriefing: Briefing = {
  id: "demo-briefing-001",
  label: "Seeded competition briefing",
  mode: "demo",
  generatedAt: "2026-10-02T18:30:00Z",
  window: "Seeded fixtures — no live claims",
  stats: {
    scanned: 1842,
    unusual: 43,
    verified: 19,
    selected: 7,
    countries: 7,
  },
  stories: [
    {
      id: "emu-roundabout",
      rank: 1,
      title: "Escaped emu turns a suburban roundabout into a two-hour police operation",
      shortTitle: "The roundabout emu",
      summary: "A demo fixture about an escaped emu repeatedly circling a busy roundabout while officers tried increasingly elaborate ways to guide it away from traffic.",
      detailedSummary: "In this seeded demonstration story, an emu gets loose near a suburban shopping district and discovers that the central island of a roundabout is an excellent place to avoid capture. Officers temporarily slow traffic, a drone is used to track the bird, and a local animal handler eventually walks it into a horse trailer with feed. Nobody is injured.",
      whyItsWeird: "The combination of an emu, rush-hour traffic, a police drone and a perfectly ordinary roundabout turns a mundane animal escape into an absurdly over-equipped standoff.",
      category: "Animals",
      tags: ["animal", "police", "traffic", "harmless"],
      country: "Australia",
      region: "Oceania",
      eventDate: "2026-09-24T07:20:00Z",
      publicationDate: "2026-09-24T10:10:00Z",
      discoveredAt: "2026-09-24T10:18:00Z",
      absurdityScore: 96,
      noveltyScore: 90,
      humorScore: 91,
      seriousnessScore: 5,
      credibilityScore: 94,
      confidence: "high",
      seriousness: "harmless",
      clusterId: "cluster-emu-01",
      sources: [
        { publisher: "Demo Local News", url: "https://example.org/demo/emu-local", publishedAt: "2026-09-24T10:10:00Z", sourceType: "demo-fixture" },
        { publisher: "Demo Police Bulletin", url: "https://example.org/demo/emu-police", publishedAt: "2026-09-24T11:00:00Z", sourceType: "demo-fixture" },
        { publisher: "Demo National Desk", url: "https://example.org/demo/emu-national", publishedAt: "2026-09-24T12:12:00Z", sourceType: "demo-fixture" }
      ],
      verificationNotes: "Seeded Demo Mode fixture. The verification trail is simulated to exercise the same UI used by Live Mode; these source links intentionally use example.org.",
      status: "selected",
      isFixture: true,
      research: [
        { label: "Discovered", detail: "Picked up from a seeded local-news candidate pool.", status: "complete", at: "10:18" },
        { label: "Article inspected", detail: "Headline, summary and timestamps normalized.", status: "complete", at: "10:19" },
        { label: "Duplicate cluster detected", detail: "Three reports mapped to one underlying event.", status: "complete", at: "10:20" },
        { label: "Corroboration found", detail: "Demo police bulletin linked as a second source.", status: "complete", at: "10:21" },
        { label: "Event date resolved", detail: "Event time kept separate from publication time.", status: "complete", at: "10:21" },
        { label: "Verification completed", detail: "High confidence inside the seeded fixture.", status: "complete", at: "10:22" },
        { label: "Selected", detail: "Ranked #1 for harmless absurdity and novelty.", status: "complete", at: "10:23" }
      ]
    },
    {
      id: "goat-council",
      rank: 2,
      title: "Goat walks into a municipal office and refuses to leave until someone finds biscuits",
      shortTitle: "The municipal goat",
      summary: "A seeded harmless story about a goat entering a public office, occupying the reception area and ignoring every attempt to remove it except food.",
      detailedSummary: "The demo scenario starts when a goat slips through an open service entrance and wanders into a municipal reception area. Staff try to guide it back outside with cardboard barriers and a mop before discovering that a packet of biscuits is the only effective negotiating instrument.",
      whyItsWeird: "It looks less like animal control and more like a small hostage negotiation conducted entirely over snacks.",
      category: "Local Chaos",
      tags: ["animal", "government", "harmless"],
      country: "South Africa",
      region: "Africa",
      eventDate: "2026-09-23T09:00:00+02:00",
      publicationDate: "2026-09-23T11:30:00+02:00",
      discoveredAt: "2026-09-23T11:34:00+02:00",
      absurdityScore: 92,
      noveltyScore: 83,
      humorScore: 94,
      seriousnessScore: 3,
      credibilityScore: 91,
      confidence: "high",
      seriousness: "harmless",
      clusterId: "cluster-goat-01",
      sources: [
        { publisher: "Demo Gauteng Desk", url: "https://example.org/demo/goat-office", publishedAt: "2026-09-23T11:30:00+02:00", sourceType: "demo-fixture" },
        { publisher: "Demo Municipal Notice", url: "https://example.org/demo/goat-notice", publishedAt: "2026-10-01T12:00:00+02:00", sourceType: "demo-fixture" }
      ],
      verificationNotes: "Seeded Demo Mode fixture with simulated corroboration.",
      status: "selected",
      isFixture: true,
      research: [
        { label: "Discovered", detail: "Seeded regional feed candidate.", status: "complete", at: "11:34" },
        { label: "Clustered", detail: "Two reports collapsed into one event.", status: "complete", at: "11:36" },
        { label: "Verified", detail: "Fixture-level municipal corroboration attached.", status: "complete", at: "11:38" },
        { label: "Selected", detail: "High humor, low seriousness.", status: "complete", at: "11:40" }
      ]
    },
    {
      id: "crab-baggage",
      rank: 3,
      title: "Airport baggage belt briefly becomes a moving parade of escaped live crabs",
      shortTitle: "Crabs on carousel four",
      summary: "A seeded story about a damaged seafood container sending live crabs onto an airport baggage carousel before staff corral them with luggage tubs.",
      detailedSummary: "A shipment container splits during handling in this demonstration fixture. Several live crabs reach a public baggage carousel, where passengers start filming while ground staff use empty luggage tubs to contain them. Operations are delayed but nobody is hurt.",
      whyItsWeird: "Baggage claim already feels theatrical; adding dozens of sideways-moving passengers makes it literal.",
      category: "Transportation",
      tags: ["airport", "animals", "travel"],
      country: "Japan",
      region: "Asia",
      eventDate: "2026-10-01T05:50:00Z",
      publicationDate: "2026-10-01T07:05:00Z",
      discoveredAt: "2026-10-01T07:12:00Z",
      absurdityScore: 88,
      noveltyScore: 85,
      humorScore: 84,
      seriousnessScore: 8,
      credibilityScore: 88,
      confidence: "medium",
      seriousness: "harmless",
      clusterId: "cluster-crab-01",
      sources: [
        { publisher: "Demo Airport Desk", url: "https://example.org/demo/crabs-airport", publishedAt: "2026-10-01T07:05:00Z", sourceType: "demo-fixture" }
      ],
      verificationNotes: "Seeded fixture with only one simulated reporting source, so confidence is medium.",
      status: "selected",
      isFixture: true,
      research: [
        { label: "Discovered", detail: "Seeded transportation feed candidate.", status: "complete", at: "07:12" },
        { label: "Inspected", detail: "Article metadata normalized.", status: "complete", at: "07:13" },
        { label: "Verification limited", detail: "Only one fixture source attached.", status: "warning", at: "07:16" },
        { label: "Selected", detail: "Strong novelty despite medium confidence.", status: "complete", at: "07:18" }
      ]
    },
    {
      id: "robot-mower",
      rank: 4,
      title: "Robot lawn mower keeps escaping a park and returning to the same bakery",
      shortTitle: "The bakery mower",
      summary: "A seeded technology story about an autonomous mower repeatedly leaving its geofenced park route and parking itself outside a bakery.",
      detailedSummary: "In the fixture, maintenance crews reset an autonomous mower three times after it exits a public park. Each time it travels roughly the same route and stops outside the same bakery, creating a very convincing appearance of preference despite an eventual diagnosis of a bad boundary beacon.",
      whyItsWeird: "A mundane navigation fault accidentally gives a garden appliance a personality and a favorite destination.",
      category: "Technology",
      tags: ["robot", "automation", "human error"],
      country: "Germany",
      region: "Europe",
      eventDate: "2026-09-30T08:00:00Z",
      publicationDate: "2026-10-01T08:20:00Z",
      discoveredAt: "2026-10-01T08:25:00Z",
      absurdityScore: 85,
      noveltyScore: 92,
      humorScore: 82,
      seriousnessScore: 2,
      credibilityScore: 93,
      confidence: "high",
      seriousness: "harmless",
      clusterId: "cluster-mower-01",
      sources: [
        { publisher: "Demo City Tech Desk", url: "https://example.org/demo/mower", publishedAt: "2026-10-01T08:20:00Z", sourceType: "demo-fixture" },
        { publisher: "Demo Parks Department", url: "https://example.org/demo/mower-parks", publishedAt: "2026-10-01T09:00:00Z", sourceType: "demo-fixture" }
      ],
      verificationNotes: "Seeded Demo Mode fixture. Simulated technical explanation attached.",
      status: "selected",
      isFixture: true,
      research: [
        { label: "Discovered", detail: "Seeded city technology feed.", status: "complete", at: "08:25" },
        { label: "Corroborated", detail: "Parks department fixture added.", status: "complete", at: "08:31" },
        { label: "Classified", detail: "Technology / Human Error.", status: "complete", at: "08:33" },
        { label: "Selected", detail: "High novelty, harmless outcome.", status: "complete", at: "08:35" }
      ]
    },
    {
      id: "foam-fountain",
      rank: 5,
      title: "Town square fountain produces a three-storey foam cloud after detergent prank",
      shortTitle: "Foam over the square",
      summary: "A seeded local-chaos story in which detergent dumped into a fountain creates a drifting foam mass large enough to close part of a town square.",
      detailedSummary: "The fixture describes maintenance crews confronting a fountain filled with detergent overnight. By morning, pumps have turned it into a foam cloud taller than nearby streetlights. The square is partially closed while crews skim and flush the system.",
      whyItsWeird: "The scale is wildly disproportionate to the simplicity of the cause: soap plus pumps equals accidental architecture.",
      category: "Human Error",
      tags: ["prank", "infrastructure", "harmless"],
      country: "Spain",
      region: "Europe",
      eventDate: "2026-10-01T04:15:00Z",
      publicationDate: "2026-10-01T08:45:00Z",
      discoveredAt: "2026-10-01T08:49:00Z",
      absurdityScore: 82,
      noveltyScore: 76,
      humorScore: 80,
      seriousnessScore: 10,
      credibilityScore: 89,
      confidence: "high",
      seriousness: "harmless",
      clusterId: "cluster-foam-01",
      sources: [
        { publisher: "Demo Iberia Local", url: "https://example.org/demo/foam", publishedAt: "2026-10-01T08:45:00Z", sourceType: "demo-fixture" },
        { publisher: "Demo City Statement", url: "https://example.org/demo/foam-city", publishedAt: "2026-10-01T09:20:00Z", sourceType: "demo-fixture" }
      ],
      verificationNotes: "Seeded Demo Mode fixture with simulated city confirmation.",
      status: "selected",
      isFixture: true,
      research: [
        { label: "Discovered", detail: "Seeded local reporting.", status: "complete", at: "08:49" },
        { label: "Event date resolved", detail: "Overnight incident separated from morning publication.", status: "complete", at: "08:53" },
        { label: "Verified", detail: "Fixture city statement linked.", status: "complete", at: "08:56" },
        { label: "Selected", detail: "Strong visual absurdity, low harm.", status: "complete", at: "08:58" }
      ]
    },
    {
      id: "library-bat",
      rank: 6,
      title: "Library pauses evening service because one bat learns the automatic doors",
      shortTitle: "The library bat",
      summary: "A seeded animal story about a bat repeatedly re-entering a library through motion-activated doors as staff try to usher it outside.",
      detailedSummary: "The fictional demo incident escalates only because the bat discovers that circling in front of the entrance triggers the doors. Staff dim lights, open windows and eventually disable the automatic sensor long enough for an animal specialist to remove it.",
      whyItsWeird: "The building's accessibility automation becomes the bat's personal re-entry system.",
      category: "Animals",
      tags: ["animal", "library", "automation"],
      country: "Canada",
      region: "North America",
      eventDate: "2026-09-30T23:10:00Z",
      publicationDate: "2026-10-01T02:40:00Z",
      discoveredAt: "2026-10-01T02:46:00Z",
      absurdityScore: 79,
      noveltyScore: 80,
      humorScore: 78,
      seriousnessScore: 2,
      credibilityScore: 87,
      confidence: "medium",
      seriousness: "harmless",
      clusterId: "cluster-bat-01",
      sources: [
        { publisher: "Demo Community Desk", url: "https://example.org/demo/library-bat", publishedAt: "2026-10-01T02:40:00Z", sourceType: "demo-fixture" }
      ],
      verificationNotes: "Seeded fixture. One simulated source, therefore medium confidence.",
      status: "selected",
      isFixture: true,
      research: [
        { label: "Discovered", detail: "Seeded community feed.", status: "complete", at: "02:46" },
        { label: "Inspected", detail: "Metadata and event time normalized.", status: "complete", at: "02:49" },
        { label: "Verification limited", detail: "No second fixture source.", status: "warning", at: "02:52" },
        { label: "Selected", detail: "Harmless and unusual enough for briefing.", status: "complete", at: "02:54" }
      ]
    },
    {
      id: "sinkhole-bus",
      rank: 7,
      title: "Parked bus drops into a sudden sinkhole; passengers had stepped off minutes earlier",
      shortTitle: "The sinkhole bus",
      summary: "A seeded serious-but-extraordinary story about a parked bus falling into a road collapse shortly after passengers had disembarked.",
      detailedSummary: "This fixture is intentionally handled without jokes. A road collapse opens beneath an empty parked bus shortly after passengers have exited. Emergency crews secure the area and inspect nearby utilities. Nobody is reported injured in the seeded scenario.",
      whyItsWeird: "The timing is extraordinary, but the event is treated as serious infrastructure news rather than comedy.",
      category: "Weather / Nature",
      tags: ["infrastructure", "sinkhole", "serious"],
      country: "Brazil",
      region: "South America",
      eventDate: "2026-10-01T12:10:00Z",
      publicationDate: "2026-10-01T13:05:00Z",
      discoveredAt: "2026-10-01T13:11:00Z",
      absurdityScore: 72,
      noveltyScore: 78,
      humorScore: 0,
      seriousnessScore: 78,
      credibilityScore: 90,
      confidence: "high",
      seriousness: "serious",
      clusterId: "cluster-sinkhole-01",
      sources: [
        { publisher: "Demo Metro Desk", url: "https://example.org/demo/sinkhole", publishedAt: "2026-10-01T13:05:00Z", sourceType: "demo-fixture" },
        { publisher: "Demo Civil Defence", url: "https://example.org/demo/sinkhole-civil", publishedAt: "2026-10-01T13:40:00Z", sourceType: "demo-fixture" }
      ],
      verificationNotes: "Seeded Demo Mode fixture. Seriousness gate suppresses humorous framing.",
      status: "selected",
      isFixture: true,
      research: [
        { label: "Discovered", detail: "Seeded metro feed candidate.", status: "complete", at: "13:11" },
        { label: "Corroborated", detail: "Civil-defence fixture attached.", status: "complete", at: "13:17" },
        { label: "Seriousness gate", detail: "Humor score forced to zero; serious tone required.", status: "complete", at: "13:18" },
        { label: "Selected", detail: "Included as serious but extraordinary news.", status: "complete", at: "13:20" }
      ]
    }
  ]
};
